# Generated by Django 2.0 on 2021-08-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
